###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Samuel Pineda",
    "age": "24",
    "email": "sapinedal@gmial.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/65d78b49da7c1c7cb7ac89df HTTP/1.1

###
PUT http://localhost:9000/api/users/65d78c4dda7c1c7cb7ac89e1 HTTP/1.1
Content-Type: application/json

{
    "name": "Yenny Lopezzz",
    "age": "44",
    "email": "notiene@gmial.com"
}

###
DELETE  http://localhost:9000/api/users/65d7a1e629c5df3d8aa5cd26 HTTP/1.1